// packages/ui-react/src/components/ChatPanel.tsx
import { useState, useRef, useEffect, type KeyboardEvent } from 'react'
import { useMessages, useMediaControls } from '../hooks.js'

interface Props {
  className?: string
}

export function ChatPanel({ className }: Props) {
  const messages = useMessages()
  const { sendMessage } = useMediaControls()
  const [text, setText] = useState('')
  const listRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (listRef.current) {
      listRef.current.scrollTop = listRef.current.scrollHeight
    }
  }, [messages])

  const handleSend = async () => {
    const trimmed = text.trim()
    if (!trimmed) return
    await sendMessage(trimmed)
    setText('')
  }

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {
      e.preventDefault()
      void handleSend()
    }
  }

  return (
    <div className={`rtc-chat-panel ${className ?? ''}`}>
      <div ref={listRef} className="rtc-chat-panel__messages" role="log" aria-live="polite" aria-relevant="additions">
        {messages.map((msg) => (
          <div key={msg.id} className="rtc-chat-panel__message">
            <strong className="rtc-chat-panel__sender">{msg.fromName}</strong>
            <span className="rtc-chat-panel__text">{msg.text}</span>
            <time className="rtc-chat-panel__time" dateTime={msg.timestamp.toISOString()}>
              {msg.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
            </time>
          </div>
        ))}
      </div>
      <div className="rtc-chat-panel__input-row">
        <textarea
          className="rtc-chat-panel__input"
          value={text}
          onChange={(e) => setText(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Type a message… (Ctrl+Enter to send)"
          rows={2}
          aria-label="Chat message"
        />
        <button
          className="rtc-chat-panel__send"
          onClick={handleSend}
          disabled={!text.trim()}
          aria-label="Send message"
        >
          Send
        </button>
      </div>
    </div>
  )
}

// packages/ui-vue/src/components/ChatPanel.vue
<script setup lang="ts">
import { ref, nextTick, watch } from 'vue'
import { useCall, useMessages } from '../composables.js'

const call = useCall()
const messages = useMessages()
const text = ref('')
const listRef = ref<HTMLElement | null>(null)

watch(messages, async () => {
  await nextTick()
  if (listRef.value) listRef.value.scrollTop = listRef.value.scrollHeight
})

async function send() {
  const t = text.value.trim()
  if (!t) return
  await call.sendMessage(t)
  text.value = ''
}

function onKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {
    e.preventDefault()
    void send()
  }
}
</script>

<template>
  <div class="rtc-chat-panel">
    <div ref="listRef" class="rtc-chat-panel__messages" role="log" aria-live="polite" aria-relevant="additions">
      <div v-for="msg in messages" :key="msg.id" class="rtc-chat-panel__message">
        <strong class="rtc-chat-panel__sender">{{ msg.fromName }}</strong>
        <span class="rtc-chat-panel__text">{{ msg.text }}</span>
        <time class="rtc-chat-panel__time" :datetime="msg.timestamp.toISOString()">
          {{ msg.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }}
        </time>
      </div>
    </div>
    <div class="rtc-chat-panel__input-row">
      <textarea
        v-model="text"
        class="rtc-chat-panel__input"
        placeholder="Type a message… (Ctrl+Enter to send)"
        rows="2"
        aria-label="Chat message"
        @keydown="onKeydown"
      />
      <button class="rtc-chat-panel__send" :disabled="!text.trim()" aria-label="Send message" @click="send">
        Send
      </button>
    </div>
  </div>
</template>
