// packages/ui-react/src/components/ControlBar.tsx
import { useState } from 'react'
import { useLocalParticipant, useMediaControls, useLayout } from '../hooks.js'
import { DeviceSelector } from './DeviceSelector.js'
import type { Layout } from '@rtcstack/sdk'

export type ControlBarButton =
  | 'mic' | 'camera' | 'screenshare'
  | 'reactions' | 'layout' | 'devices' | 'leave'

const ALL_BUTTONS: ControlBarButton[] = ['mic', 'camera', 'screenshare', 'reactions', 'layout', 'devices', 'leave']
const REACTIONS = ['👍', '❤️', '😂', '🎉', '👏', '🙌']

interface Props {
  className?: string
  onLeave?: () => void
  buttons?: ControlBarButton[]
}

export function ControlBar({ className, onLeave, buttons = ALL_BUTTONS }: Props) {
  const local = useLocalParticipant()
  const { toggleMic, toggleCamera, toggleScreenShare, sendReaction, disconnect } = useMediaControls()
  const { layout, setLayout } = useLayout()
  const [devicesOpen, setDevicesOpen] = useState(false)

  const show = (btn: ControlBarButton) => buttons.includes(btn)

  const handleLeave = async () => {
    await disconnect()
    onLeave?.()
  }

  const nextLayout: Layout = layout === 'grid' ? 'spotlight' : 'grid'

  return (
    <div className={`rtc-control-bar ${className ?? ''}`} role="toolbar" aria-label="Call controls" style={{ position: 'relative' }}>
      {devicesOpen && (
        <DeviceSelector className="rtc-control-bar__devices-popover" />
      )}

      {show('mic') && (
        <button
          className={`rtc-control-bar__btn ${local?.isMuted ? 'rtc-control-bar__btn--off' : ''}`}
          onClick={toggleMic}
          aria-pressed={local?.isMuted}
          aria-label={local?.isMuted ? 'Unmute microphone' : 'Mute microphone'}
        >
          {local?.isMuted ? '🎤✕' : '🎤'}
        </button>
      )}

      {show('camera') && (
        <button
          className={`rtc-control-bar__btn ${local?.isCameraOff ? 'rtc-control-bar__btn--off' : ''}`}
          onClick={toggleCamera}
          aria-pressed={local?.isCameraOff}
          aria-label={local?.isCameraOff ? 'Turn camera on' : 'Turn camera off'}
        >
          {local?.isCameraOff ? '📷✕' : '📷'}
        </button>
      )}

      {show('screenshare') && (
        <button
          className={`rtc-control-bar__btn ${local?.isScreenSharing ? 'rtc-control-bar__btn--active' : ''}`}
          onClick={toggleScreenShare}
          aria-pressed={local?.isScreenSharing}
          aria-label={local?.isScreenSharing ? 'Stop sharing screen' : 'Share screen'}
        >
          {local?.isScreenSharing ? '🖥✕' : '🖥'}
        </button>
      )}

      {show('reactions') && (
        <div className="rtc-control-bar__reactions" role="group" aria-label="Send reaction">
          {REACTIONS.map((emoji) => (
            <button
              key={emoji}
              className="rtc-control-bar__btn rtc-control-bar__btn--reaction"
              onClick={() => sendReaction(emoji)}
              aria-label={`React with ${emoji}`}
            >
              {emoji}
            </button>
          ))}
        </div>
      )}

      {show('layout') && (
        <button
          className="rtc-control-bar__btn"
          onClick={() => setLayout(nextLayout)}
          aria-label={`Switch to ${nextLayout} layout`}
          title={`Switch to ${nextLayout} layout`}
        >
          {layout === 'grid' ? '⊞' : '⊟'}
        </button>
      )}

      {show('devices') && (
        <button
          className={`rtc-control-bar__btn ${devicesOpen ? 'rtc-control-bar__btn--active' : ''}`}
          onClick={() => setDevicesOpen((v) => !v)}
          aria-pressed={devicesOpen}
          aria-label="Device settings"
          title="Device settings"
        >
          ⚙
        </button>
      )}

      {show('leave') && (
        <button
          className="rtc-control-bar__btn rtc-control-bar__btn--danger"
          onClick={handleLeave}
          aria-label="Leave call"
        >
          Leave
        </button>
      )}
    </div>
  )
}

// packages/ui-vue/src/components/ControlBar.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useCall, useLocalParticipant, useLayout } from '../composables.js'
import DeviceSelector from './DeviceSelector.vue'

export type ControlBarButton =
  | 'mic' | 'camera' | 'screenshare'
  | 'reactions' | 'layout' | 'devices' | 'leave'

const ALL_BUTTONS: ControlBarButton[] = ['mic', 'camera', 'screenshare', 'reactions', 'layout', 'devices', 'leave']

const props = withDefaults(defineProps<{
  buttons?: ControlBarButton[]
}>(), {
  buttons: () => ALL_BUTTONS,
})

const emit = defineEmits<{ leave: [] }>()
const call = useCall()
const local = useLocalParticipant()
const { layout, setLayout } = useLayout()

const isMuted = computed(() => local.value?.isMuted ?? true)
const isCameraOff = computed(() => local.value?.isCameraOff ?? true)
const isScreenSharing = computed(() => local.value?.isScreenSharing ?? false)
const devicesOpen = ref(false)

const REACTIONS = ['👍', '❤️', '😂', '🎉', '👏', '🙌']

const show = (btn: ControlBarButton) => props.buttons.includes(btn)

async function toggleMic() { await call.toggleMic() }
async function toggleCamera() { await call.toggleCamera() }
async function toggleScreenShare() {
  if (isScreenSharing.value) await call.stopScreenShare()
  else await call.startScreenShare()
}
async function sendReaction(emoji: string) { await call.sendReaction(emoji) }
async function handleLeave() {
  await call.disconnect()
  emit('leave')
}
function toggleLayout() {
  setLayout(layout.value === 'grid' ? 'spotlight' : 'grid')
}
</script>

<template>
  <div class="rtc-control-bar" role="toolbar" aria-label="Call controls" style="position:relative">
    <DeviceSelector v-if="devicesOpen" class="rtc-control-bar__devices-popover" />

    <button
      v-if="show('mic')"
      class="rtc-control-bar__btn"
      :class="{ 'rtc-control-bar__btn--off': isMuted }"
      :aria-pressed="isMuted"
      :aria-label="isMuted ? 'Unmute microphone' : 'Mute microphone'"
      @click="toggleMic"
    >
      {{ isMuted ? '🎤✕' : '🎤' }}
    </button>

    <button
      v-if="show('camera')"
      class="rtc-control-bar__btn"
      :class="{ 'rtc-control-bar__btn--off': isCameraOff }"
      :aria-pressed="isCameraOff"
      :aria-label="isCameraOff ? 'Turn camera on' : 'Turn camera off'"
      @click="toggleCamera"
    >
      {{ isCameraOff ? '📷✕' : '📷' }}
    </button>

    <button
      v-if="show('screenshare')"
      class="rtc-control-bar__btn"
      :class="{ 'rtc-control-bar__btn--active': isScreenSharing }"
      :aria-pressed="isScreenSharing"
      :aria-label="isScreenSharing ? 'Stop sharing screen' : 'Share screen'"
      @click="toggleScreenShare"
    >
      {{ isScreenSharing ? '🖥✕' : '🖥' }}
    </button>

    <div v-if="show('reactions')" class="rtc-control-bar__reactions" role="group" aria-label="Send reaction">
      <button
        v-for="emoji in REACTIONS"
        :key="emoji"
        class="rtc-control-bar__btn rtc-control-bar__btn--reaction"
        :aria-label="`React with ${emoji}`"
        @click="sendReaction(emoji)"
      >{{ emoji }}</button>
    </div>

    <button
      v-if="show('layout')"
      class="rtc-control-bar__btn"
      :title="`Switch to ${layout === 'grid' ? 'spotlight' : 'grid'} layout`"
      @click="toggleLayout"
    >
      {{ layout === 'grid' ? '⊞' : '⊟' }}
    </button>

    <button
      v-if="show('devices')"
      class="rtc-control-bar__btn"
      :class="{ 'rtc-control-bar__btn--active': devicesOpen }"
      :aria-pressed="devicesOpen"
      aria-label="Device settings"
      title="Device settings"
      @click="devicesOpen = !devicesOpen"
    >⚙</button>

    <button
      v-if="show('leave')"
      class="rtc-control-bar__btn rtc-control-bar__btn--danger"
      aria-label="Leave call"
      @click="handleLeave"
    >
      Leave
    </button>
  </div>
</template>
