// packages/ui-react/src/components/DeviceSelector.tsx
import { useState, useEffect } from 'react'
import { useDevices, useMediaControls } from '../hooks.js'

type DeviceKind = 'audioinput' | 'audiooutput' | 'videoinput'

interface GroupProps {
  label: string
  icon: string
  devices: MediaDeviceInfo[]
  selected: string
  onChange: (id: string) => void
}

function DeviceGroup({ label, icon, devices, selected, onChange }: GroupProps) {
  if (devices.length === 0) return null
  return (
    <div className="rtc-device-selector__group">
      <label className="rtc-device-selector__label">
        <span className="rtc-device-selector__icon">{icon}</span>
        {label}
      </label>
      <select
        className="rtc-device-selector__select"
        value={selected}
        onChange={(e) => onChange(e.target.value)}
        aria-label={`Select ${label}`}
      >
        {devices.map((d) => (
          <option key={d.deviceId} value={d.deviceId}>
            {d.label || `${label} ${devices.indexOf(d) + 1}`}
          </option>
        ))}
      </select>
    </div>
  )
}

interface Props {
  className?: string
}

export function DeviceSelector({ className }: Props) {
  const devices = useDevices()
  const { switchDevice } = useMediaControls()
  const [selected, setSelected] = useState<Record<DeviceKind, string>>({
    audioinput: '',
    audiooutput: '',
    videoinput: '',
  })

  // Seed initial selection from first device in each list
  useEffect(() => {
    setSelected((prev) => ({
      audioinput: prev.audioinput || devices.audioinput[0]?.deviceId || '',
      audiooutput: prev.audiooutput || devices.audiooutput[0]?.deviceId || '',
      videoinput: prev.videoinput || devices.videoinput[0]?.deviceId || '',
    }))
  }, [devices])

  function handleChange(kind: DeviceKind, deviceId: string) {
    setSelected((prev) => ({ ...prev, [kind]: deviceId }))
    void switchDevice(kind, deviceId)
  }

  return (
    <div className={`rtc-device-selector ${className ?? ''}`} role="dialog" aria-label="Device settings">
      <div className="rtc-device-selector__header">Device Settings</div>
      <DeviceGroup
        label="Microphone"
        icon="🎤"
        devices={devices.audioinput}
        selected={selected.audioinput}
        onChange={(id) => handleChange('audioinput', id)}
      />
      <DeviceGroup
        label="Speaker"
        icon="🔊"
        devices={devices.audiooutput}
        selected={selected.audiooutput}
        onChange={(id) => handleChange('audiooutput', id)}
      />
      <DeviceGroup
        label="Camera"
        icon="📷"
        devices={devices.videoinput}
        selected={selected.videoinput}
        onChange={(id) => handleChange('videoinput', id)}
      />
    </div>
  )
}

// packages/ui-vue/src/components/DeviceSelector.vue
<script setup lang="ts">
import { ref, watchEffect } from 'vue'
import { useCall, useDevices } from '../composables.js'

type DeviceKind = 'audioinput' | 'audiooutput' | 'videoinput'

const call = useCall()
const devices = useDevices()

const selected = ref<Record<DeviceKind, string>>({
  audioinput: '',
  audiooutput: '',
  videoinput: '',
})

// Seed first available device when list populates
watchEffect(() => {
  if (!selected.value.audioinput && devices.value.audioinput[0])
    selected.value.audioinput = devices.value.audioinput[0].deviceId
  if (!selected.value.audiooutput && devices.value.audiooutput[0])
    selected.value.audiooutput = devices.value.audiooutput[0].deviceId
  if (!selected.value.videoinput && devices.value.videoinput[0])
    selected.value.videoinput = devices.value.videoinput[0].deviceId
})

async function onChange(kind: DeviceKind, deviceId: string) {
  selected.value[kind] = deviceId
  await call.switchDevice(kind, deviceId)
}
</script>

<template>
  <div class="rtc-device-selector" role="dialog" aria-label="Device settings">
    <div class="rtc-device-selector__header">Device Settings</div>

    <div v-if="devices.audioinput.length" class="rtc-device-selector__group">
      <label class="rtc-device-selector__label">
        <span class="rtc-device-selector__icon">🎤</span>Microphone
      </label>
      <select
        class="rtc-device-selector__select"
        :value="selected.audioinput"
        aria-label="Select microphone"
        @change="onChange('audioinput', ($event.target as HTMLSelectElement).value)"
      >
        <option v-for="(d, i) in devices.audioinput" :key="d.deviceId" :value="d.deviceId">
          {{ d.label || `Microphone ${i + 1}` }}
        </option>
      </select>
    </div>

    <div v-if="devices.audiooutput.length" class="rtc-device-selector__group">
      <label class="rtc-device-selector__label">
        <span class="rtc-device-selector__icon">🔊</span>Speaker
      </label>
      <select
        class="rtc-device-selector__select"
        :value="selected.audiooutput"
        aria-label="Select speaker"
        @change="onChange('audiooutput', ($event.target as HTMLSelectElement).value)"
      >
        <option v-for="(d, i) in devices.audiooutput" :key="d.deviceId" :value="d.deviceId">
          {{ d.label || `Speaker ${i + 1}` }}
        </option>
      </select>
    </div>

    <div v-if="devices.videoinput.length" class="rtc-device-selector__group">
      <label class="rtc-device-selector__label">
        <span class="rtc-device-selector__icon">📷</span>Camera
      </label>
      <select
        class="rtc-device-selector__select"
        :value="selected.videoinput"
        aria-label="Select camera"
        @change="onChange('videoinput', ($event.target as HTMLSelectElement).value)"
      >
        <option v-for="(d, i) in devices.videoinput" :key="d.deviceId" :value="d.deviceId">
          {{ d.label || `Camera ${i + 1}` }}
        </option>
      </select>
    </div>
  </div>
</template>
