// packages/ui-vue/src/components/ParticipantVideo.vue
<script setup lang="ts">
import { ref, watchEffect, computed, onUnmounted } from 'vue'
import type { Participant } from '@rtcstack/sdk'

const props = withDefaults(defineProps<{
  participant: Participant
  isScreenShare?: boolean
  showSpeakingIndicator?: boolean
  showMuteIndicator?: boolean
  showQualityBadge?: boolean
  showName?: boolean
  mirror?: boolean
  objectFit?: 'cover' | 'contain'
}>(), {
  isScreenShare: false,
  showSpeakingIndicator: true,
  showMuteIndicator: true,
  showQualityBadge: true,
  showName: true,
  objectFit: 'cover',
})

const emit = defineEmits<{ click: [] }>()

const videoRef = ref<HTMLVideoElement | null>(null)
const audioRef = ref<HTMLAudioElement | null>(null)

watchEffect(() => {
  const track = props.isScreenShare ? props.participant.screenShareTrack : props.participant.videoTrack
  if (videoRef.value && track) {
    videoRef.value.srcObject = new MediaStream([track])
  } else if (videoRef.value) {
    videoRef.value.srcObject = null
  }
})

watchEffect(() => {
  if (audioRef.value && props.participant.audioTrack && !props.participant.isLocal) {
    audioRef.value.srcObject = new MediaStream([props.participant.audioTrack])
    audioRef.value.play().catch(() => {})
  }
})

onUnmounted(() => {
  if (videoRef.value) videoRef.value.srcObject = null
  if (audioRef.value) audioRef.value.srcObject = null
})

const QUALITY_MAP: Record<string, { bars: number; color: string }> = {
  excellent: { bars: 3, color: '#2ecc71' },
  good:      { bars: 2, color: '#f39c12' },
  poor:      { bars: 1, color: '#e74c3c' },
  lost:      { bars: 0, color: '#e74c3c' },
  unknown:   { bars: 0, color: '#666' },
}

const qualityBars = computed(() => QUALITY_MAP[props.participant.connectionQuality]?.bars ?? 0)
const qualityColor = computed(() => QUALITY_MAP[props.participant.connectionQuality]?.color ?? '#666')
const shouldMirror = computed(() => props.mirror ?? (!props.isScreenShare && props.participant.isLocal))
const hasVideo = computed(() => !!(props.isScreenShare ? props.participant.screenShareTrack : props.participant.videoTrack))
</script>

<template>
  <div
    class="rtc-participant-tile"
    :class="{
      'rtc-participant-tile--speaking': participant.isSpeaking && !isScreenShare,
      'rtc-participant-tile--screenshare': isScreenShare,
    }"
    :data-participant-id="participant.id"
    @click="emit('click')"
  >
    <video
      ref="videoRef"
      autoplay
      playsinline
      muted
      class="rtc-participant-tile__video"
      :class="{
        'rtc-participant-tile__video--mirrored': shouldMirror,
        'rtc-participant-tile__video--hidden': !hasVideo,
      }"
      :style="{ objectFit }"
    />
    <audio v-if="!participant.isLocal && !isScreenShare" ref="audioRef" autoplay playsinline />

    <div v-if="!hasVideo && !isScreenShare" class="rtc-participant-tile__avatar" aria-hidden="true">
      <span class="rtc-participant-tile__initials">{{ participant.name.charAt(0).toUpperCase() }}</span>
    </div>

    <div v-if="showName || showSpeakingIndicator || showMuteIndicator || showQualityBadge" class="rtc-participant-tile__info">
      <span v-if="showName" class="rtc-participant-tile__name">
        {{ isScreenShare ? `${participant.name}'s screen` : participant.name }}
      </span>
      <span v-if="!isScreenShare && showSpeakingIndicator && participant.isSpeaking" class="rtc-participant-tile__speaking-icon" aria-label="Speaking">🎙</span>
      <span v-if="!isScreenShare && showMuteIndicator && participant.isMuted" class="rtc-participant-tile__muted" aria-label="Muted">🔇</span>
      <span v-if="!isScreenShare && showQualityBadge" class="rtc-quality-badge" :aria-label="`Quality: ${participant.connectionQuality}`">
        <span
          v-for="n in [1, 2, 3]"
          :key="n"
          class="rtc-quality-badge__bar"
          :style="{ height: `${4 + n * 3}px`, background: n <= qualityBars ? qualityColor : 'rgba(255,255,255,0.2)' }"
        />
      </span>
    </div>

    <span v-if="participant.isScreenSharing && !isScreenShare" class="rtc-participant-tile__screen-badge" aria-label="Screen sharing">🖥</span>
  </div>
</template>

// packages/ui-react/src/components/ParticipantVideo.tsx
import { useEffect, useRef } from 'react'
import type { Participant } from '@rtcstack/sdk'
import { ConnectionQualityBadge } from './ConnectionQualityBadge.js'

export interface ParticipantVideoProps {
  participant: Participant
  isScreenShare?: boolean
  className?: string
  onClick?: () => void
  showSpeakingIndicator?: boolean
  showMuteIndicator?: boolean
  showQualityBadge?: boolean
  showName?: boolean
  mirror?: boolean
  objectFit?: 'cover' | 'contain'
}

export function ParticipantVideo({
  participant,
  isScreenShare = false,
  className,
  onClick,
  showSpeakingIndicator = true,
  showMuteIndicator = true,
  showQualityBadge = true,
  showName = true,
  mirror,
  objectFit = 'cover',
}: ParticipantVideoProps) {
  const videoRef = useRef<HTMLVideoElement>(null)
  const audioRef = useRef<HTMLAudioElement>(null)

  const track = isScreenShare ? participant.screenShareTrack : participant.videoTrack
  const shouldMirror = mirror ?? (!isScreenShare && participant.isLocal)

  useEffect(() => {
    if (videoRef.current && track) {
      videoRef.current.srcObject = new MediaStream([track])
    } else if (videoRef.current) {
      videoRef.current.srcObject = null
    }
  }, [track])

  useEffect(() => {
    if (audioRef.current && participant.audioTrack && !participant.isLocal) {
      audioRef.current.srcObject = new MediaStream([participant.audioTrack])
      audioRef.current.play().catch(() => {})
    }
  }, [participant.audioTrack, participant.isLocal])

  const hasVideo = !!track
  const showAvatar = !hasVideo && !isScreenShare

  return (
    <div
      className={[
        'rtc-participant-tile',
        participant.isSpeaking && !isScreenShare ? 'rtc-participant-tile--speaking' : '',
        isScreenShare ? 'rtc-participant-tile--screenshare' : '',
        className ?? '',
      ].join(' ').trim()}
      data-participant-id={participant.id}
      onClick={onClick}
      style={onClick ? { cursor: 'pointer' } : undefined}
    >
      <video
        ref={videoRef}
        autoPlay
        playsInline
        muted
        className={[
          'rtc-participant-tile__video',
          shouldMirror ? 'rtc-participant-tile__video--mirrored' : '',
          !hasVideo ? 'rtc-participant-tile__video--hidden' : '',
        ].join(' ').trim()}
        style={{ objectFit }}
      />
      {!participant.isLocal && !isScreenShare && (
        <audio ref={audioRef} autoPlay playsInline />
      )}

      {showAvatar && (
        <div className="rtc-participant-tile__avatar" aria-hidden="true">
          <span className="rtc-participant-tile__initials">
            {participant.name.charAt(0).toUpperCase()}
          </span>
        </div>
      )}

      {(showName || showSpeakingIndicator || showMuteIndicator || showQualityBadge) && (
        <div className="rtc-participant-tile__info">
          {showName && (
            <span className="rtc-participant-tile__name">
              {isScreenShare ? `${participant.name}'s screen` : participant.name}
            </span>
          )}
          {!isScreenShare && showSpeakingIndicator && participant.isSpeaking && (
            <span className="rtc-participant-tile__speaking-icon" aria-label="Speaking">
              🎙
            </span>
          )}
          {!isScreenShare && showMuteIndicator && participant.isMuted && (
            <span className="rtc-participant-tile__muted" aria-label="Muted">
              🔇
            </span>
          )}
          {!isScreenShare && showQualityBadge && (
            <ConnectionQualityBadge quality={participant.connectionQuality} />
          )}
        </div>
      )}

      {participant.isScreenSharing && !isScreenShare && (
        <span className="rtc-participant-tile__screen-badge" aria-label="Screen sharing">
          🖥
        </span>
      )}
    </div>
  )
}
