// packages/ui-vue/src/components/TranscriptPanel.vue
<script setup lang="ts">
import { watch, nextTick, ref } from 'vue'
import { useTranscription, useSpeakingIndicators } from '../composables.js'

withDefaults(defineProps<{
  maxItems?: number
  showSpeakerName?: boolean
}>(), {
  maxItems: 100,
  showSpeakerName: true,
})

const transcripts = useTranscription()
const speaking = useSpeakingIndicators()
const bottomRef = ref<HTMLElement | null>(null)

watch([transcripts, speaking], async () => {
  await nextTick()
  bottomRef.value?.scrollIntoView({ behavior: 'smooth' })
}, { deep: true })
</script>

<template>
  <div class="rtc-transcript-panel" role="log" aria-live="polite" aria-label="Live transcript">
    <div
      v-for="(seg, i) in maxItems > 0 ? transcripts.slice(-maxItems) : transcripts"
      :key="i"
      class="rtc-transcript-panel__entry"
    >
      <span v-if="showSpeakerName" class="rtc-transcript-panel__speaker">{{ seg.speaker }}</span>
      <span class="rtc-transcript-panel__text">{{ seg.text }}</span>
    </div>
    <div
      v-for="[id, name] in speaking"
      :key="`interim-${id}`"
      class="rtc-transcript-panel__entry rtc-transcript-panel__entry--interim"
    >
      <span v-if="showSpeakerName" class="rtc-transcript-panel__speaker">{{ name }}</span>
      <span class="rtc-transcript-panel__text rtc-transcript-panel__text--interim" aria-label="Speaking">···</span>
    </div>
    <div ref="bottomRef" />
  </div>
</template>

// packages/ui-react/src/components/TranscriptPanel.tsx
import { useEffect, useRef } from 'react'
import { useTranscription, useSpeakingIndicators } from '../hooks.js'

interface Props {
  className?: string
  maxItems?: number
  showSpeakerName?: boolean
}

export function TranscriptPanel({ className, maxItems = 100, showSpeakerName = true }: Props) {
  const segments = useTranscription()
  const speaking = useSpeakingIndicators()
  const bottomRef = useRef<HTMLDivElement>(null)

  const visible = maxItems > 0 ? segments.slice(-maxItems) : segments

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [segments.length, speaking.size])

  return (
    <div className={`rtc-transcript-panel ${className ?? ''}`} role="log" aria-live="polite" aria-label="Live transcript">
      {visible.map((seg, i) => (
        <div key={i} className="rtc-transcript-panel__entry">
          {showSpeakerName && (
            <span className="rtc-transcript-panel__speaker">{seg.speaker}</span>
          )}
          <span className="rtc-transcript-panel__text">{seg.text}</span>
        </div>
      ))}
      {[...speaking.entries()].map(([id, name]) => (
        <div key={`interim-${id}`} className="rtc-transcript-panel__entry rtc-transcript-panel__entry--interim">
          {showSpeakerName && (
            <span className="rtc-transcript-panel__speaker">{name}</span>
          )}
          <span className="rtc-transcript-panel__text rtc-transcript-panel__text--interim" aria-label="Speaking">···</span>
        </div>
      ))}
      <div ref={bottomRef} />
    </div>
  )
}
